apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    description: "Default storage class for application configuration volumes"
provisioner: driver.longhorn.io
parameters:
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
