statefulset:
  heimdall:
    image:
      repository: linuxserver/heimdall
      tag: latest
  replicas: 1
service:
  ports:
  - port: 6969
    protocol: TCP
    targetPort: 80
  type: ClusterIP
ingress:
  rules:
    host: heimdall.mediabox.local
    secretName: heimdall-tls
    http:
      service:
        name: heimdall-service
