apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  labels:
    app: ombi
    {{- include "ombi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn