statefulset:
  replicas: 1
  sabnzbd:
    image:
      repository: linuxserver/sabnzbd
      tag: latest
    resources:
      limits:
        cpu: "1"
        memory: 2G
      requests:
        cpu: "1"
        memory: 2G
service:
  ports:
  - port: 5052
    protocol: TCP
    targetPort: 5052
  type: LoadBalancer # Changed from ClusterIP
ingress:
  rules:
    host: sabnzbd.mediabox.local
