apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  labels:
    app: lidarr
  {{- include "lidarr.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
