apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lidarr.fullname" . }}-statefulset
  labels:
    app: lidarr
  {{- include "lidarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: lidarr
      {{- include "lidarr.selectorLabels" . | nindent 6 }}
  serviceName: lidarr-service
  template:
    metadata:
      labels:
        app: lidarr
        {{- include "lidarr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.statefulset.lidarr.image.repository }}:{{ .Values.statefulset.lidarr.image.tag | default .Chart.AppVersion }}
        name: lidarr
        ports:
        - containerPort: 8686
          name: lidarr
        volumeMounts:
        - mountPath: /config
          name: lidarr-config
        - mountPath: /mnt/ # Reverted mount point for shared media volume
          name: media-pv-data
      nodeSelector:
        app: {{ .Values.statefulset.lidarr.nodeSelector.app }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: lidarr-config
        persistentVolumeClaim:
           claimName: lidarr-config
      - name: media-pv-data
        persistentVolumeClaim:
          claimName: media-pv-pvc-claim
