apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  labels:
    app: plex
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
