{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gluetun.fullname" . }}-ingress
  labels:
  {{- include "gluetun.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.rules.host }} 
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.service.ports | first | get "port" }}
        pathType: ImplementationSpecific
{{- end }}
