{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-starter-chart.fullname" . }}
  labels:
    {{- include "helm-starter-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "helm-starter-chart.fullname" $ }} # Use the main service name
                port:
                  # Use the name of the first service port by default, or allow override
                  name: {{ $.Values.service.ports | first | get "name" }}
                  # Alternatively, specify by number if needed:
                  # number: {{ $.Values.service.ports | first | get "port" }}
          {{- end }}
    {{- end }}
{{- end }}
