apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-starter-chart.fullname" . }}
  labels:
    {{- include "helm-starter-chart.labels" . | nindent 4 }}
  # Optional: Add annotations from values if needed
  # {{- with .Values.service.annotations }}
  # annotations:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "helm-starter-chart.selectorLabels" . | nindent 4 }}
  # Optional: Add loadBalancerIP, externalTrafficPolicy etc. from values if needed
  # {{- if eq .Values.service.type "LoadBalancer" }}
  # {{- if .Values.service.loadBalancerIP }}
  # loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  # {{- end }}
  # {{- if .Values.service.externalTrafficPolicy }}
  # externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  # {{- end }}
  # {{- end }}
