statefulset:
  app: # App-specific key, replace 'app' with the actual app name when using this chart
    nodeSelector:
      app: mediabox
    image:
      repository: ""
      tag: latest
  replicas: 1
service:
  ports:
  - port: 8080 # Default port, should be updated for specific app
    protocol: TCP
    targetPort: 8080 # Should match the port value
  type: LoadBalancer
ingress:
  enabled: false
  rules:
    host: app.mediabox.local # Default host, should be updated for specific app
