apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-starter-chart.fullname" . }}-service
  labels:
  {{- include "helm-starter-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: qbittorrent
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 -}}
